<%
props.put("title_en-mx", "Online Registration - Event Ticketing, Venue Seating with Eventbee");
props.put("description_en-mx", "Easy to use online Event Management solution that includes Online Registration, Event Ticketing, Event Promotion and Membership Management");
props.put("keywords_en-mx", "events, sell tickets, online registration, event ticketing, social ticketing, event promotion, paypal payments, google check out, facebook events, ning events, party tickets, sports tickets, venue seating");
props.put("sign_up_en-mx", "Sign Up");
props.put("contact_en-mx", "Contact");
props.put("faq_en-mx", "FAQ");
props.put("log_in_en-mx", "Login");
props.put("award_win_en-mx", "Award Winning Ticketing Platform");
props.put("trust_by_en-mx", "Trusted by over 40,000 event managers across the world");
props.put("how-it-works_en-mx", "How it works");
props.put("flat-fee-pricing_en-mx", "Flat fee pricing");
props.put("immediate-access_en-mx", "Immediate access to funds");
props.put("eventbee-inc_en-mx", "Eventbee Inc. &copy; 2016");
props.put("terms-of-service_en-mx", "Terms of Service");
props.put("privacy-statement_en-mx", "Privacy Statement");
props.put("colombia_en-mx", "Colombia");
props.put("country_en-mx", "Countries");
props.put("languages_en-mx", "Languages");
props.put("log_out_en-mx", "Logout");
props.put("my_account_en-mx", "My Account");
props.put("contact_ebee_en-mx", "Contact Eventbee");
props.put("get_my_tkts_en-mx", "Get My Tickets");

//newly added.
props.put("Use_it_for_free_en-mx","Use it for free");
props.put("Eventbee_is_free_to_use_en-mx","Eventbee is free to use");
props.put("when_your_ticket_are_free_en-mx","when your ticket are free.");
props.put("Use_all_of_our_exclusive_en-mx","Use all of our exclusive");
props.put("features_at_no_cost_en-mx","features at no cost.");
props.put("We'll_bundle_the_free_into_en-mx","We'll bundle the free into");
props.put("your_ticketare_price_so_you_can_en-mx","your ticketare price so you can");
props.put("focus_on_the_important_stuff_en-mx","focus on the important stuff.");
props.put("credit_card_processing_en-mx", "Credit Card Processing");
props.put("featured_events_en-mx","FEATURED EVENTS");
props.put("check_current_eventbee_en-mx","Check out current events using Eventbee! ");
props.put("enter_event_or_venue_en-mx","Enter event or venue ");
props.put("find_events_en-mx","Find Events ");
props.put("inter_conf_edu_en-mx","2016 international confernce on Education ");
props.put("immediate_acc_fuds_en-mx","Immediate access to funds ");
props.put("sell_tick_dir_thr_fb_en-mx","Sell tickets directly through facebook  ");
props.put("free_kindle_fire_something_en-mx","Free kindle fire when you do something or another   ");
props.put("learn_more_en-mx","Learn More  ");
props.put("copyright_eventbee_all_right_reserved_en-mx","Copyright 2003 - 2016. Eventbee Inc. All Rights Reserved.  ");
props.put("privacy_statement_en-mx","Privacy Statement ");
props.put("term_of_services_en-mx","Terms Of Service");
props.put("with_backing_magr_world_records_sales_promotion_en-mx","With the backing of more than 40,000 managers in events around the world records online ticket sales and event promotion.");
props.put("create_en-mx", "Create");
props.put("promote_en-mx", "Promote");
props.put("manage_en-mx", "Manage");
props.put("basic_en-mx", "Basic");
props.put("ticket_en-mx", "Ticket");
props.put("view_savings_en-mx", "View Savings");
props.put("hide_savings_en-mx", "Hide Savings");
props.put("start_saving_en-mx", "Start Saving");
props.put("current_provider_en-mx", "Current Provider");
props.put("ticket_prices_en-mx", "Ticket Prices");
props.put("ticket_amount_en-mx", "Ticket Amount");
props.put("event_brite_en-mx", "Eventbrite");
props.put("ticket_leap_en-mx", "Ticketleap");
props.put("ticket_master_en-mx", "Ticketmaster");
props.put("otro_en-mx", "Otro");
props.put("set_up_your_event_page_en-mx", "Set up your event page");
props.put("create_single_or_multiple_ticket_types_en-mx", "Create single or multiple ticket types");
props.put("make_it_one_time_or_recurring_en-mx", "Make it a one time or recurring event");
props.put("allow_general_admission_or_reserved_seationg_en-mx", "Allow general admission or reserved seating");
props.put("establishes_genreral_reserved_seating_en-mx", "Establishes general or reserved seating tickets");
props.put("customize_your_event_en-mx", "Customize your event");
props.put("setup_dynamic_registration_en-mx", "Setup dynamic registration form");
props.put("design_branded_look_and_feel_en-mx", "Design branded look and feel");
props.put("customize_your_confirmation_email_en-mx", "Customize your confirmation email");
props.put("flexible_credit_card_processing_en-mx", "Flexible credit card processing");
props.put("choose_paypal_stripe_braintree_auth_net_eventbee_en-mx", "Choose PayPal, Stripe, Braintree, Authorize.net or Eventbee");
props.put("immediate_access_to funds_with_pay_pal_stripe_brain_net_en-mx", "Immediate access to funds with PayPal, Stripe, Braintree or Authorize.net");
props.put("for_seamless_credit_card_processing_choose_event_en-mx", "For seamless credit card processing, choose Eventbee");
props.put("publicize_your_even_page_en-mx", "Publicize your event page");
props.put("place_the_event_link_on_your_website_and_your_mails_en-mx", "Place the event link on your website and in your emails");
props.put("dispaly_our_event_ticket_widget_on_your_website_en-mx", " Display our event tickets widget on your website");
props.put("add_the_event_link_your_print_media_en-mx", "Add the event link to your print media");
props.put("social_media_sharing_en-mx", "Social media sharing");
props.put("enable_t_g_s_en-mx", "Enable Facebook, Twitter, Google+ sharing");
props.put("allow_facebook_commenting_your_event_page_en-mx", " Allow Facebook commenting on your event page");
props.put("reward_attendees_for_social_sharing_en-mx", "Reward attendees for social sharing");
props.put("facebook_fan_page_ticketing_en-mx", "Facebook fan page ticketing");
props.put("dispaly_buy_tickets_tab_your_fan_page_en-mx", " Display Buy Tickets tab on your fan page");
props.put("allow_fan_buy_ticket_through_facebook_en-mx", " Allow fans to buy tickets through Facebook");
props.put("Customize_which_events_to_display_on_your_fan_page_en-mx", "Customize which events to display on your fan page");
props.put("Streamline_Event_Management_en-mx", "Streamline Event Management");
props.put("Add_sub_managers_to_your_event_and_delegate_tasks_en-mx", " Add sub-managers to your event and delegate tasks");
props.put("Email_attendees_with_one_click_to_give_event_updates_en-mx", " Email attendees with one click to give event updates");
props.put("Access_your_account_24/7_to_make_any_changes_en-mx", "  Access your account 24/7 to make any changes");
props.put("Extensive_Reporting_en-mx", "Extensive Reporting");
props.put("Gather_Attendee_data_en-mx", " Gather Attendee data");
props.put("Generate_sales_reports_en-mx", "  Generate sales reports");
props.put("Export_reports_to_Excel_or_PDFs_en-mx", " Export reports to Excel or PDF");
props.put("At_The_Door_en-mx", "At The Door");
props.put("Use_Eventbee_mobile_app_to_check_in_attendees_en-mx", " Use Eventbee mobile app to check-in attendees");
props.put("Scan_QR_code_or_barcode_for_faster_check_in_en-mx", " Scan QR code or barcode for faster check-in");
props.put("Sell_tickets_and_process_credit_cards_with_Eventbee_Manager_app_en-mx", " Sell tickets and process credit cards with Eventbee Manager app");
props.put("Immediate_access_to_your_funds_en-mx","Immediate access to your funds");
props.put("Optinal_processing_at_en-mx","Optinal processing at");
props.put("Extra_customization_to_give_en-mx","Extra customization to give");
props.put("you_an_edge_in_making_your_en-mx","you an edge in making your");
props.put("event_unique1_en-mx"," event unique.");
props.put("advanced_en-mx","Advanced");
props.put("Business_en-mx","Business");
props.put("saved_en-mx","Saved");
props.put("Ticket_price_en-mx","Ticket Price");
props.put("Ticket_Quantity_en-mx","Ticket Quantity");


props.put("title_es-mx", "Registro en línea - Evento venta de entradas, de estar Venue con Eventbee");
props.put("description_es-mx", "Fácil de usar solución de gestión de eventos en línea que incluye registro en línea, eventos de venta de entradas, promoción de eventos y gestión de Membresía");
props.put("keywords_es-mx", "eventos, venta de billetes, la inscripción en línea, eventos de venta de entradas, venta de entradas social, la promoción de eventos, los pagos de PayPal, Google echa un vistazo, eventos de Facebook, eventos Ning, entradas de partidos, entradas de deportes, Asientos en el lugar");
props.put("sign_up_es-mx", "Registrarse");
props.put("contact_es-mx", "Contacto");
props.put("faq_es-mx", "Preguntas Frecuentes");
props.put("log_in_es-mx", "Iniciar sesión");
props.put("award_win_es-mx", "PLATAFORMA GALARDONADA EN VENTA DE TIQUETES");
props.put("trust_by_es-mx", "Respaldada por más de 40.000 administradores de eventos en todo el mundo");
props.put("how-it-works_es-mx", "Cómo funciona");
props.put("flat-fee-pricing_es-mx", "Precios de tarifa fija");
props.put("immediate-access_es-mx", "Acceso inmediato a tus fondos");
props.put("eventbee-inc_es-mx", "Eventbee Inc. &copy; 2016");
props.put("terms-of-service_es-mx", "Términos de Servicio");
props.put("privacy-statement_es-mx", "Declaración de privacidad");
props.put("colombia_es-mx", "Colombia");
props.put("country_es-mx", "Países");
props.put("languages_es-mx", "idiomas");
props.put("log_out_es-mx", "Cerrar sesión");
props.put("my_account_es-mx", "Mi cuenta");
props.put("contact_ebee_es-mx", "Contactar a Eventbee");
props.put("get_my_tkts_es-mx", "Obtener mis tiquetes");

//newly added.
props.put("featured_events_es-mx","Eventos especiales");
props.put("check_current_eventbee_es-mx","Echa un vistazo a los acontecimientos actuales utilizando Eventbee!");
props.put("enter_event_or_venue_es-mx","Introduzca los acontecimiento o lugar ");
props.put("find_events_es-mx","Encuentre Eventos ");
props.put("inter_conf_edu_es-mx","2016 conferencia internacional sobre Educación");
props.put("immediate_acc_fuds_es-mx","El acceso inmediato a los fondos");
props.put("sell_tick_dir_thr_fb_es-mx","Venta entradas directamente a través de facebook  ");
props.put("free_kindle_fire_something_es-mx","Libre enciende el fuego cuando haces algo u otro   ");
props.put("learn_more_es-mx","Aprende más  ");
props.put("copyright_eventbee_all_right_reserved_es-mx","Derechos de Autor 2003 hasta 2.015. Eventbee Inc. Reservados todos los derechos.  ");
props.put("privacy_statement_es-mx","Declaración de Privacidad  ");
props.put("term_of_services_es-mx","Términos de servicio ");
props.put("with_backing_magr_world_records_sales_promotion_es-mx","Con el respaldo de más de 40.000 gerentes en eventos alrededor del mundo registra la venta de entradas en línea y promoción de eventos.");
props.put("create_es-mx", "Crear");
props.put("promote_es-mx", "Promover");
props.put("manage_es-mx", "Administrar");
props.put("basic_es-mx", "Básico");
props.put("ticket_es-mx", "Billete");
props.put("view_savings_es-mx", "Ver Ahorros");
props.put("hide_savings_es-mx", "Ocultar Ahorros");
props.put("start_saving_es-mx", "Comience a ahorrar");
props.put("current_provider_es-mx", "Proveedor Actual");
props.put("ticket_prices_es-mx", "Precio de los boletos");
props.put("ticket_amount_es-mx", "Cantidad de Tiquetes");
props.put("event_brite_es-mx", "Eventbrite");
props.put("ticket_leap_es-mx", "Ticketleap");
props.put("otro_es-mx", "Otro");
props.put("ticket_master_es-mx", "Ticketmaster");
props.put("otro_es-mx", "Otro");
props.put("credit_card_processing_es-mx", "Procesamiento de Tarjetas de Crédito");
props.put("set_up_your_event_page_es-mx", "Crea tu página de eventos ");
props.put("create_single_or_multiple_ticket_types_es-mx", "Crea uno o múltiples tipos de tiquetes");
props.put("make_it_one_time_or_recurring_es-mx", "Crea tiquetes para eventos únicos o individuales");
props.put("allow_general_admission_or_reserved_seationg_es-mx", "Crea tiquetes para eventos recurrentes o periódicos");
props.put("establishes_genreral_reserved_seating_es-mx", "Establece entradas generales o asientos reservados ");
props.put("customize_your_event_es-mx", "Personaliza tu evento ");
props.put("setup_dynamic_registration_es-mx", "Crea formatos de registro dinámicos");
props.put("design_branded_look_and_feel_es-mx", "Diseña la apariencia y estilo de tu marca");
props.put("customize_your_confirmation_email_es-mx", "Personaliza tus correos de confirmación");
props.put("flexible_credit_card_processing_es-mx", "Procesos de pago flexibles");
props.put("choose_paypal_stripe_braintree_auth_net_eventbee_es-mx", "Elige entre Paypal, Stripe, Braintree, Authorize.net o Eventbee");
props.put("immediate_access_to funds_with_pay_pal_stripe_brain_net_es-mx", "Acceso inmediato a fondos con PayPal, Stripe, Braintree o Authorize.net");
props.put("for_seamless_credit_card_processing_choose_event_es-mx", "    Para un mejor proceso de pago, elige Eventbee");
props.put("publicize_your_even_page_es-mx", "Haz pública la página de tu evento");
props.put("place_the_event_link_on_your_website_and_your_mails_es-mx", "Publica el link del evento en tu página web o por correo");
props.put("dispaly_our_event_ticket_widget_on_your_website_es-mx", "  Visualiza el widget de los tiquetes de tu evento en tu página web");
props.put("add_the_event_link_your_print_media_es-mx", "Difunde el link del evento en tus redes sociales");
props.put("social_media_sharing_es-mx", "Comparte en tus redes sociales");
props.put("enable_t_g_s_es-mx", " Habilita la opción de compartir para Facebook, Twitter y Google+");
props.put("allow_facebook_commenting_your_event_page_es-mx", " Permite los comentarios de Facebook en la página de tu evento");
props.put("reward_attendees_for_social_sharing_es-mx", "Recompensa a los asistentes que comparten tu evento en sus redes sociales");
props.put("facebook_fan_page_ticketing_es-mx", "Vende Tiquetes a través de tu página de seguidores en Facebook");
props.put("dispaly_buy_tickets_tab_your_fan_page_es-mx", " Habilita el botón 'Comprar Tiquetes' en tu página de seguidores");
props.put("allow_fan_buy_ticket_through_facebook_es-mx", "Permítele a tus fans comprar tiquetes a través de Facebook");
props.put("Customize_which_events_to_display_on_your_fan_page_es-mx", "Personaliza cuál evento quieres que se visualice en tu página de seguidores");
props.put("Streamline_Event_Management_es-mx", "Optimiza la gestión de tus eventos");
props.put("Add_sub_managers_to_your_event_and_delegate_tasks_es-mx", "Agrega Co-Administradores a tus eventos y asígnales tareas");
props.put("Email_attendees_with_one_click_to_give_event_updates_es-mx", " Envía correos a tus asistentes sólo con un clic para informarles a cerca de actualizaciones");
props.put("Access_your_account_24/7_to_make_any_changes_es-mx", "  Accede a tu cuenta 24/7 para realizar cualquier cambio");
props.put("Extensive_Reporting_es-mx", "Maximiza tus reportes");
props.put("Gather_Attendee_data_es-mx", " Recopila datos de tu asistentes");
props.put("Generate_sales_reports_es-mx", " Genera informes de ventas");
props.put("Export_reports_to_Excel_or_PDFs_es-mx", " Exporta tus informes a Excel o PDF");
props.put("At_The_Door_es-mx", "Aplicaciones Eventbee");
props.put("Use_Eventbee_mobile_app_to_check_in_attendees_es-mx", " Usa la aplicación móvil Eventbee para chequear asistentes");
props.put("Scan_QR_code_or_barcode_for_faster_check_in_es-mx", "  Escanéa los códigos QR y códigos de barras para realizar un chequeo más rápido");
props.put("Sell_tickets_and_process_credit_cards_with_Eventbee_Manager_app_es-mx", "Vende tiquetes y realiza pagos con la aplicación Eventbee");
props.put("Immediate_access_to_your_funds_es-mx","El acceso inmediato a sus fondos");
props.put("Optinal_processing_at_es-mx","Procesamiento óptimo en");
props.put("Extra_customization_to_give_es-mx","Personalización complementaria para dar");
props.put("you_an_edge_in_making_your_es-mx","que una ventaja en hacer su");
props.put("event_unique1_es-mx","evento único.");
props.put("advanced_es-mx","Avanzado");
props.put("Business_es-mx","Negocio");
props.put("saved_es-mx","Salvado");
props.put("Ticket_price_es-mx","Precio de la entrada");
props.put("Ticket_Quantity_es-mx","Cantidad de entradas");
props.put("Use_it_for_free_es-mx","Utilizar de forma gratuita");
props.put("Eventbee_is_free_to_use_es-mx","Eventbee es de uso gratuito");
props.put("when_your_ticket_are_free_es-mx","cuando su boleto son gratis.");
props.put("Use_all_of_our_exclusive_es-mx","Utilizar todos nuestros diseños exclusivos");
props.put("features_at_no_cost_es-mx","características sin costo alguno.");
props.put("We'll_bundle_the_free_into_es-mx","Vamos a agrupar en la libre");
props.put("your_ticketare_price_so_you_can_es-mx","billete es el precio por lo que puede");
props.put("focus_on_the_important_stuff_es-mx","centrarse en las cosas importantes.");
%>