<%@ page import="java.util.*,com.eventbee.general.EbeeCachingManager" %>
<%

HashMap blockedUsers=(HashMap)EbeeCachingManager.ebeeCache.get("blocked_user_urls");
HashMap blockedCustomURLs=(HashMap)EbeeCachingManager.ebeeCache.get("blocked_custom_urls");
HashMap blockedEvents=(HashMap)EbeeCachingManager.ebeeCache.get("blockedEvents");
%>
<style type="text/css">
.actionbtn {
	-moz-box-shadow:inset 0px 0px 0px 0px #fce2c1;
	-webkit-box-shadow:inset 0px 0px 0px 0px #fce2c1;
	box-shadow:inset 0px 0px 0px 0px #fce2c1;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #e8850c), color-stop(1, #fb9e25) );
	background:-moz-linear-gradient( center top, #e8850c 5%, #fb9e25 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#e8850c', endColorstr='#fb9e25');
	background-color:#e8850c;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #eeb44f;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:3px 14px;
	text-decoration:none;
	text-shadow:1px 1px 0px #cc9f52;
}.actionbtn:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fb9e25), color-stop(1, #e8850c) );
	background:-moz-linear-gradient( center top, #fb9e25 5%, #e8850c 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fb9e25', endColorstr='#e8850c');
	background-color:#fb9e25;
}.actionbtn:active {
	position:relative;
	top:1px;
}
/******************************************************************************************/
.sumtable {

	margin:0px;padding:0px;

	width:550px;
	box-shadow: 5px 5px 5px #888888;

	border:1px solid #000000;

	

	-moz-border-radius-bottomleft:0px;

	-webkit-border-bottom-left-radius:0px;

	border-bottom-left-radius:0px;

	

	-moz-border-radius-bottomright:0px;

	-webkit-border-bottom-right-radius:0px;

	border-bottom-right-radius:0px;

	

	-moz-border-radius-topright:0px;

	-webkit-border-top-right-radius:0px;

	border-top-right-radius:0px;

	

	-moz-border-radius-topleft:0px;

	-webkit-border-top-left-radius:0px;

	border-top-left-radius:0px;

}.sumtable table{

	width:100%;
	margin:0px;padding:0px;

}.sumtable tr:last-child td:last-child {

	-moz-border-radius-bottomright:0px;

	-webkit-border-bottom-right-radius:0px;

	border-bottom-right-radius:0px;

}

.sumtable table tr:first-child td:first-child {

	-moz-border-radius-topleft:0px;

	-webkit-border-top-left-radius:0px;

	border-top-left-radius:0px;

}

.sumtable table tr:first-child td:last-child {

	-moz-border-radius-topright:0px;

	-webkit-border-top-right-radius:0px;

	border-top-right-radius:0px;

}.sumtable tr:last-child td:first-child{

	-moz-border-radius-bottomleft:0px;

	-webkit-border-bottom-left-radius:0px;

	border-bottom-left-radius:0px;

}.sumtable tr:hover td{
}
.sumtable tr:nth-child(odd){ background-color:#aad4ff; }

.sumtable tr:nth-child(even)    { background-color:#ffffff; }
.sumtable td{
	vertical-align:middle;
	border:1px solid #000000;
	border-width:0px 1px 1px 0px;
	text-align:left;
	padding:4px;
	font-size:12px;
	font-family:Arial;
	font-weight:normal;
	color:#000000;
}.sumtable tr:last-child td{
	border-width:0px 1px 0px 0px;
}.sumtable tr td:last-child{
	border-width:0px 0px 1px 0px;
}.sumtable tr:last-child td:last-child{
	border-width:0px 0px 0px 0px;
}
.sumtable tr:first-child td{
		background:-o-linear-gradient(bottom, #005fbf 5%, #003f7f 100%);	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #005fbf), color-stop(1, #003f7f) );
	background:-moz-linear-gradient( center top, #005fbf 5%, #003f7f 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#005fbf", endColorstr="#003f7f");	background: -o-linear-gradient(top,#005fbf,003f7f);
	background-color:#005fbf;
	border:0px solid #000000;
	text-align:center;
	border-width:0px 0px 1px 1px;
	font-size:12px;
	font-family:Arial;
	font-weight:bold;
	color:#ffffff;
}

.sumtable tr:first-child:hover td{
	background:-o-linear-gradient(bottom, #005fbf 5%, #003f7f 100%);	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #005fbf), color-stop(1, #003f7f) );
	background:-moz-linear-gradient( center top, #005fbf 5%, #003f7f 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#005fbf", endColorstr="#003f7f");	background: -o-linear-gradient(top,#005fbf,003f7f);
	background-color:#005fbf;
}
.sumtable tr:first-child td:first-child{
	border-width:0px 0px 1px 0px;
}
.sumtable tr:first-child td:last-child{
	border-width:0px 0px 1px 1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
<script>
	function submitBlockingForm(action,purpose){
		if(purpose=='user'){
			document.userform.elements["action"].value=action;
			document.userform.submit();
		}else if(purpose=='customurl'){
			document.customurlform.elements["action"].value=action;
			document.customurlform.submit();
		}else if(purpose=='event'){
			document.eventform.elements["action"].value=action;
			document.eventform.submit();
		}
	}
</script>

<fieldset>
<legend><b>Blocked Users</b></legend>
<div id="blockedusers">
	<form action="/utworks/manageblockedcache.jsp" name="userform">
	<table >
		<tr>
			<td>
				Add User <input type="text" name="key">	
				<input type="hidden" name="purpose" value="user">
				<input type="hidden" name="action" value="">	
			</td>
			<td>
				<a href="#" class="actionbtn" onclick="submitBlockingForm('add','user');">Add</a>
				<a href="#" class="actionbtn" onclick="submitBlockingForm('delete','user');">Delete</a>
				<!--<input type="button" value="Add" onclick="submitBlockingForm('add','user');">
				<input type="button" value="Delete" onclick="submitBlockingForm('delete','user');">-->
			</td>
		</tr>
	</table>
	</form>
	
	<%
		if(blockedUsers!=null && blockedUsers.size()>0){
		 Iterator it = blockedUsers.entrySet().iterator();
		 %>
		 <div class="sumtable">
		 <table >
		 <tr><td><b>Login Name</b></td><td><b>Action</b></td></tr>
		 <%
		 while (it.hasNext()){
			Map.Entry pairs = (Map.Entry)it.next();
			String key=(String)pairs.getKey();
	%>
		<tr>
			<td><%=key%></td><td><a href="/utworks/manageblockedcache.jsp?key=<%=key%>&purpose=user&action=delete">Delete</a></td>
		</tr>
	<%}%>
		</table>
		</div>
	<%}%>
</div>
<div style="height: 20px;"> </div>
<a href="/utworks/manageblockedcache.jsp?purpose=user&action=deleteall" class="actionbtn" >Delete All</a>
</fieldset>
<div style="height: 20px;"> </div>
<fieldset>
<legend><b>Blocked Custom URLs</b></legend>
<div id="blockedusers">
	<form action="/utworks/manageblockedcache.jsp" name="customurlform">
	<table>
		<tr>
			<td>
				Add custom URL <input type="text" name="key">	
				<input type="hidden" name="purpose" value="customurl">	
				<input type="hidden" name="action" value="">
			</td>
			<td>
				<a href="#" class="actionbtn" onclick="submitBlockingForm('add','customurl')">Add</a>
				<a href="#" class="actionbtn" onclick="submitBlockingForm('delete','customurl')">Delete</a>
				<!--<input type="button" value="Add" onclick="submitBlockingForm('add','customurl')">
				<input type="button" value="Delete" onclick="submitBlockingForm('delete','customurl')">-->
			</td>
		</tr>
	</table>
	</form>

	<%
		if(blockedCustomURLs!=null && blockedCustomURLs.size()>0){
		 Iterator it = blockedCustomURLs.entrySet().iterator();
		  %>
		  <div class="sumtable">
		 <table>
		 <tr><td>Custom URL</td><td>Action</td></tr>
		 <%
		 while (it.hasNext()){
			Map.Entry pairs = (Map.Entry)it.next();
			String key=(String)pairs.getKey();
	%>
		<tr>
			<td><%=key%></td><td><a href="/utworks/manageblockedcache.jsp?key=<%=key%>&purpose=customurl&action=delete">Delete</a></td>
		</tr>
	<%}%>
		</table>
		</div>
	<%}%>
</div>
<div style="height: 20px;"> </div>
<a href="/utworks/manageblockedcache.jsp?purpose=customurl&action=deleteall" class="actionbtn">Delete All</a>
</fieldset>
<div style="height: 20px;"> </div>
<fieldset>
<legend><b>Blocked Events</b></legend>
<div id="blockedusers">
	<form action="/utworks/manageblockedcache.jsp" name="eventform">
	<table>
		<tr>
			<td>
				Add Event <input type="text" name="key">	
				<input type="hidden" name="purpose" value="event">	
				<input type="hidden" name="action" value="">
			</td>
			<td>
				<a href="#" class="actionbtn" onclick="submitBlockingForm('add','event')">Add</a>
				<a href="#" class="actionbtn" onclick="submitBlockingForm('delete','event')">Delete</a>
<!--
				<input type="button" value="Add" onclick="submitBlockingForm('add','event')">
				<input type="button" value="Delete" onclick="submitBlockingForm('delete','event')">-->
			</td>
		</tr>
	</table>
	</form>
	
	<%
		if(blockedEvents!=null && blockedEvents.size()>0){
		 Iterator it = blockedEvents.entrySet().iterator();
		  %>
		  <div class="sumtable">
		  <table >
		 <tr><td>Event Id</td><td>Action</td></tr>
		 <%
		 while (it.hasNext()){
			Map.Entry pairs = (Map.Entry)it.next();
			String key=(String)pairs.getKey();
	%>
		<tr>
			<td><%=key%></td><td><a href="/utworks/manageblockedcache.jsp?key=<%=key%>&purpose=event&action=delete">Delete</a></td>
		</tr>
	<%}%>
		</table>
		</div>
	<%}%>
	<div style="height: 20px;"> </div>
	<a href="/utworks/manageblockedcache.jsp?purpose=event&action=deleteall" class="actionbtn" >Delete All</a>
</div>
</fieldset>
